/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cinema.ui;
import com.cinema.entities.Film;
import com.cinema.services.FilmService;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author ZAKIA AZIZI
 */

public class FilmForm extends javax.swing.JInternalFrame {
    private FilmService filmService = new FilmService();

    /**
     * Creates new form FilmForm
     */
public FilmForm() {
    initComponents(); 
    
    chargerFilms(); 
   this.setSize(900, 600);
   this.setLocation(20, 20);
    
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int ligne = jTable1.getSelectedRow();
            jTextField1.setText(jTable1.getValueAt(ligne, 1).toString());
            jTextField2.setText(jTable1.getValueAt(ligne, 2).toString());
            jSpinner1.setValue(jTable1.getValueAt(ligne, 3));
            jTextField3.setText(jTable1.getValueAt(ligne, 4).toString());
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des films");

        jPanel1.setLayout(null);

        jLabel1.setText("Titre:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 70, 16);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(189, 10, 90, 22);

        jLabel2.setText("Genre:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 40, 39, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(189, 40, 90, 22);

        jLabel3.setText("Durée:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 80, 41, 16);
        jPanel1.add(jSpinner1);
        jSpinner1.setBounds(190, 70, 90, 22);

        jLabel4.setText("Realisateur:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 110, 90, 16);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(190, 110, 90, 22);

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modifier");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Vider");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Titre", "Genre", "Durée", "Réalisateur"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) jTable1.getModel();

    Object[] ligne = new Object[5];

    ligne[0] = model.getRowCount() + 1;
    ligne[1] = jTextField1.getText();
    ligne[2] = jTextField2.getText();
    ligne[3] = jSpinner1.getValue();
    ligne[4] = jTextField3.getText();

    model.addRow(ligne);

    jTextField1.setText("");
    jTextField2.setText("");
    jSpinner1.setValue(0);
    jTextField3.setText("");

        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   try {
    // Récupérer les valeurs des champs
    String titre = jTextField1.getText().trim();
    String genre = jTextField2.getText().trim();
    int duree = (int) jSpinner1.getValue();
    String realisateur = jTextField3.getText().trim();
    
    // Validation
    if (titre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Le titre est obligatoire");
        return;
    }
    if (genre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Le genre est obligatoire");
        return;
    }
    if (duree <= 0) {
        JOptionPane.showMessageDialog(this, "La durée doit être positive");
        return;
    }
    
    // Créer un objet Film
    Film film = new Film();
    film.setTitre(titre);
    film.setGenre(genre);
    film.setDuree(duree);
    film.setRealisateur(realisateur);
    
    // Sauvegarder dans la BD
    boolean success = filmService.createFilm(film);
    
    if (success) {
        JOptionPane.showMessageDialog(this, "Film ajouté avec succès !");
        chargerFilms(); // Recharger le tableau
        viderChamps();
    } else {
        JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout du film");
    }
    
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Erreur: " + e.getMessage());
}
   
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 
viderChamps();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
private void viderChamps() {
    jTextField1.setText("");
    jTextField2.setText("");
    jSpinner1.setValue(0);
    jTextField3.setText("");
    jTable1.clearSelection();
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int ligneSelectionnee = jTable1.getSelectedRow();

if (ligneSelectionnee != -1) {
    int confirm = JOptionPane.showConfirmDialog(this,
            "Voulez-vous vraiment supprimer ce film ?",
            "Confirmation",
            JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        // Récupérer l'ID du film
        int id = (int) jTable1.getValueAt(ligneSelectionnee, 0);
        
        // Supprimer de la BD
        boolean success = filmService.deleteFilm(id);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Film supprimé avec succès !");
            chargerFilms(); // Recharger le tableau
            viderChamps();
        } else {
            JOptionPane.showMessageDialog(this, "Erreur lors de la suppression");
        }
    }
} else {
    JOptionPane.showMessageDialog(this,
            "Sélectionnez une ligne à supprimer");
}
   
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    // Récupérer le modèle
int ligneSelectionnee = jTable1.getSelectedRow();

if (ligneSelectionnee != -1) {
    try {
        // Récupérer l'ID du film
        int id = (int) jTable1.getValueAt(ligneSelectionnee, 0);
        
        // Récupérer les nouvelles valeurs
        String titre = jTextField1.getText().trim();
        String genre = jTextField2.getText().trim();
        int duree = (int) jSpinner1.getValue();
        String realisateur = jTextField3.getText().trim();
        
        // Validation
        if (titre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Le titre est obligatoire");
            return;
        }
        
        // Créer l'objet Film
        Film film = new Film();
        film.setId(id);
        film.setTitre(titre);
        film.setGenre(genre);
        film.setDuree(duree);
        film.setRealisateur(realisateur);
        
        // Mettre à jour dans la BD
        boolean success = filmService.updateFilm(film);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Film modifié avec succès !");
            chargerFilms(); // Recharger le tableau
            viderChamps();
        } else {
            JOptionPane.showMessageDialog(this, "Erreur lors de la modification");
        }
        
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur: " + e.getMessage());
    }
} else {
    JOptionPane.showMessageDialog(this,
            "Sélectionnez une ligne à modifier !");
}

        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       int ligne = jTable1.getSelectedRow();

    jTextField1.setText(jTable1.getValueAt(ligne, 1).toString());
    jTextField2.setText(jTable1.getValueAt(ligne, 2).toString());
    jSpinner1.setValue(jTable1.getValueAt(ligne, 3));
    jTextField3.setText(jTable1.getValueAt(ligne, 4).toString());
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

/**
 * Charge les films depuis la base de données et les affiche dans le tableau
 */
private void chargerFilms() {
    try {
        // Récupérer le modèle du tableau
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Vider le tableau
        
        // Récupérer les films depuis la BD
        List<Film> films = filmService.getAllFilms();
        System.out.println("Chargement de " + films.size() + " films depuis la BD");
        
        // Remplir le tableau
        for (Film film : films) {
            model.addRow(new Object[]{
                film.getId(),
                film.getTitre(),
                film.getGenre(),
                film.getDuree(),
                film.getRealisateur()
            });
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, 
            "Erreur lors du chargement des films: " + e.getMessage(),
            "Erreur", 
            JOptionPane.ERROR_MESSAGE);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
