/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cinema.ui;
import javax.swing.table.DefaultTableModel;
import com.cinema.entities.Salle;
import com.cinema.services.SalleService;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author ZAKIA AZIZI
 */
public class SalleForm extends javax.swing.JInternalFrame {
    private SalleService salleService = new SalleService();

    /**
     * Creates new form SalleForm
     */
public SalleForm() {
    initComponents();
    this.setSize(900,600);
    this.setLocation(20, 20);
    
    // 1. D'abord configurer le modèle de la table
    jTable1.setModel(new DefaultTableModel(
        new Object[][]{},
        new String[]{"ID", "Nom", "Capacité"}
    ));
    
    // 2. Puis charger les données
    chargerSalles();
    
    // 3. Enfin ajouter le listener
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int ligne = jTable1.getSelectedRow();
            if (ligne != -1) {
                jTextField2.setText(jTable1.getValueAt(ligne, 1).toString()); // Nom
                jSpinner1.setValue(jTable1.getValueAt(ligne, 2)); // Capacité
            }
        }
    });
    
    jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 500, 1));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des salles");

        jPanel1.setLayout(new java.awt.GridLayout(3, 0));

        jLabel3.setText("Id:");
        jPanel1.add(jLabel3);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);

        jLabel1.setText("Nom:");
        jPanel1.add(jLabel1);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);

        jLabel2.setText("Capacité:");
        jPanel1.add(jLabel2);
        jPanel1.add(jSpinner1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nom", "Capacité"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jScrollPane1.setViewportView(jScrollPane2);

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setText("Vider");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
    String nom = jTextField2.getText().trim();
    int capacite = (int) jSpinner1.getValue();
    
    if (nom.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Le nom est obligatoire");
        return;
    }
    if (capacite <= 0) {
        JOptionPane.showMessageDialog(this, "La capacité doit être positive");
        return;
    }
    
    Salle salle = new Salle();
    salle.setNom(nom);
    salle.setCapacite(capacite);
    
    boolean success = salleService.createSalle(salle);
    
    if (success) {
        JOptionPane.showMessageDialog(this, "Salle ajoutée avec succès !");
        chargerSalles();
        viderChamps();
    } else {
        JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout");
    }
    
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Erreur: " + e.getMessage());
}
        


// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 int ligneSelectionnee = jTable1.getSelectedRow();

if (ligneSelectionnee != -1) {
    try {
        int id = (int) jTable1.getValueAt(ligneSelectionnee, 0);
        String nom = jTextField2.getText().trim();
        int capacite = (int) jSpinner1.getValue();
        
        if (nom.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Le nom est obligatoire");
            return;
        }
        
        Salle salle = new Salle();
        salle.setId(id);
        salle.setNom(nom);
        salle.setCapacite(capacite);
        
        boolean success = salleService.updateSalle(salle);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Salle modifiée avec succès !");
            chargerSalles();
            viderChamps();
        } else {
            JOptionPane.showMessageDialog(this, "Erreur lors de la modification");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur: " + e.getMessage());
    }
} else {
    JOptionPane.showMessageDialog(this, "Sélectionnez une ligne à modifier");
}
      

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    int ligneSelectionnee = jTable1.getSelectedRow();

if (ligneSelectionnee != -1) {
    int confirm = JOptionPane.showConfirmDialog(this,
            "Voulez-vous vraiment supprimer cette salle ?",
            "Confirmation",
            JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        int id = (int) jTable1.getValueAt(ligneSelectionnee, 0);
        boolean success = salleService.deleteSalle(id);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Salle supprimée avec succès !");
            chargerSalles();
            viderChamps();
        } else {
            JOptionPane.showMessageDialog(this, "Erreur lors de la suppression");
        }
    }
} else {
    JOptionPane.showMessageDialog(this, "Sélectionnez une ligne à supprimer");
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
viderChamps();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
private void viderChamps() {
    jTextField2.setText("");
    jSpinner1.setValue(1);
    jTable1.clearSelection();
}
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
private void chargerSalles() {
    try {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        List<Salle> salles = salleService.getAllSalles();
        System.out.println("Chargement de " + salles.size() + " salles depuis la BD");
        
        for (Salle s : salles) {
            model.addRow(new Object[]{
                s.getId(),
                s.getNom(),
                s.getCapacite()
            });
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, 
            "Erreur lors du chargement des salles: " + e.getMessage(),
            "Erreur", 
            JOptionPane.ERROR_MESSAGE);
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
