/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cinema.ui;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.cinema.entities.Film;
import com.cinema.entities.Salle;
import com.cinema.entities.Seance;
import com.cinema.services.FilmService;
import com.cinema.services.SalleService;
import com.cinema.services.SeanceService;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


public class SeanceForm extends javax.swing.JInternalFrame {
private SeanceService seanceService = new SeanceService();
private FilmService filmService = new FilmService();
private SalleService salleService = new SalleService();
private List<Film> listeFilms;
private List<Salle> listeSalles;
    /**
     * Creates new form SeanceForm
     */
   public SeanceForm() {
    initComponents();
    
    // Configurer le spinner de prix (à faire en premier)
    jSpinner1.setModel(new SpinnerNumberModel(50.0, 0.0, 1000.0, 5.0));
    
    // Charger les données
    chargerFilms();
    chargerSalles();
    
    // Remplir les ComboBox avec les données
    remplirComboBoxFilms();
    remplirComboBoxSalles();
    
    // Charger les séances
    chargerSeances();
    
    // Ajuster les colonnes (une seule méthode)
    ajusterColonnes();
    
    // Définir la taille et position
    this.setSize(950, 650);
    this.setLocation(20, 20);
    
    // Ajouter le listener pour la table
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int ligne = jTable1.getSelectedRow();
            if (ligne != -1) {
                remplirChampsDepuisTable(ligne);
            }
        }
    });
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Film:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 60, 40);

        jLabel2.setText("Salle:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 33, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(160, 20, 80, 22);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(160, 50, 80, 22);

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(270, 10, 108, 150);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 394, 80);

        jLabel3.setText("Date:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 31, 16);
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(160, 80, 100, 22);

        jLabel4.setText("Prix:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 110, 26, 16);
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(160, 110, 80, 22);

        jLabel5.setText("Ticket:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 140, 39, 16);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(159, 140, 80, 22);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Film", "Salle", "Date", "Prix", "Tickets"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(2, 170, 500, 180);

        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(280, 90, 100, 25);

        jButton4.setText("Vider");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(280, 130, 90, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // Modifier
int ligneSelectionnee = jTable1.getSelectedRow();

if (ligneSelectionnee != -1) {
    try {
        int id = (int) jTable1.getValueAt(ligneSelectionnee, 0);
        int indexFilm = jComboBox1.getSelectedIndex();
        int indexSalle = jComboBox2.getSelectedIndex();
        Date date = jDateChooser2.getDate();
        double prix = (double) jSpinner1.getValue();
        int tickets = Integer.parseInt(jTextField1.getText().trim());
        
        if (indexFilm == -1 || indexSalle == -1 || date == null) {
            JOptionPane.showMessageDialog(this, "Tous les champs doivent être remplis");
            return;
        }
        
        Film film = listeFilms.get(indexFilm);
        Salle salle = listeSalles.get(indexSalle);
        
        LocalDateTime dateTime = date.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDateTime();
        
        Seance seance = new Seance();
        seance.setId(id);
        seance.setFilm(film);
        seance.setSalle(salle);
        seance.setDateProjection(dateTime);
        seance.setPrix(prix);
        seance.setTicketsVendus(tickets);
        
        boolean success = seanceService.updateSeance(seance);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Séance modifiée avec succès !");
            chargerSeances();
            viderChamps();
        } else {
            JOptionPane.showMessageDialog(this, "Erreur lors de la modification (salle peut-être déjà occupée)");
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Le nombre de tickets doit être un nombre valide");
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur: " + e.getMessage());
    }
} else {
    JOptionPane.showMessageDialog(this, "Sélectionnez une ligne à modifier !");
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
int ligneSelectionnee = jTable1.getSelectedRow();

if (ligneSelectionnee != -1) {
    int confirm = JOptionPane.showConfirmDialog(this,
            "Voulez-vous vraiment supprimer cette séance ?",
            "Confirmation de suppression",
            JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            int id = (int) jTable1.getValueAt(ligneSelectionnee, 0);
            
            boolean success = seanceService.deleteSeance(id);
            
            if (success) {
                JOptionPane.showMessageDialog(this, "Séance supprimée avec succès !");
                chargerSeances();
                viderChamps();
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de la suppression");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erreur: " + e.getMessage());
        }
    }
} else {
    JOptionPane.showMessageDialog(this, "Sélectionnez une ligne à supprimer !");
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        // Vider champs
viderChamps();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   // Ajouter
        try {
    int indexFilm = jComboBox1.getSelectedIndex();
    int indexSalle = jComboBox2.getSelectedIndex();
    Date date = jDateChooser2.getDate();
    double prix = (double) jSpinner1.getValue();
    int tickets = Integer.parseInt(jTextField1.getText().trim());
    
    if (indexFilm == -1) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un film");
        return;
    }
    if (indexSalle == -1) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner une salle");
        return;
    }
    if (date == null) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner une date");
        return;
    }
    if (prix <= 0) {
        JOptionPane.showMessageDialog(this, "Le prix doit être positif");
        return;
    }
    if (tickets < 0) {
        JOptionPane.showMessageDialog(this, "Le nombre de tickets ne peut être négatif");
        return;
    }
    
    Film film = listeFilms.get(indexFilm);
    Salle salle = listeSalles.get(indexSalle);
    
    if (tickets > salle.getCapacite()) {
        JOptionPane.showMessageDialog(this, 
            "Le nombre de tickets (" + tickets + ") dépasse la capacité de la salle (" + salle.getCapacite() + ")");
        return;
    }
    
    LocalDateTime dateTime = date.toInstant()
            .atZone(ZoneId.systemDefault())
            .toLocalDateTime();
    
    Seance seance = new Seance();
    seance.setFilm(film);
    seance.setSalle(salle);
    seance.setDateProjection(dateTime);
    seance.setPrix(prix);
    seance.setTicketsVendus(tickets);
    
    boolean success = seanceService.createSeance(seance);
    
    if (success) {
        JOptionPane.showMessageDialog(this, "Séance ajoutée avec succès !");
        chargerSeances();
        viderChamps();
    } else {
        JOptionPane.showMessageDialog(this, "Erreur: cette salle est déjà occupée à cette date");
    }
    
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Le nombre de tickets doit être un nombre valide");
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Erreur: " + e.getMessage());
}
    
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
private void chargerFilms() {
    try {
        listeFilms = filmService.getAllFilms();
        System.out.println("✅ " + listeFilms.size() + " films chargés");
    } catch (Exception e) {
        e.printStackTrace();
        listeFilms = new ArrayList<>();
    }
}
private void chargerSalles() {
    try {
        listeSalles = salleService.getAllSalles();
        System.out.println("✅ " + listeSalles.size() + " salles chargées");
    } catch (Exception e) {
        e.printStackTrace();
        listeSalles = new ArrayList<>();
    }
}
private void remplirComboBoxFilms() {
    jComboBox1.removeAllItems();
    for (Film f : listeFilms) {
        jComboBox1.addItem(f.getTitre());
    }
}
private void remplirComboBoxSalles() {
    jComboBox2.removeAllItems();
    for (Salle s : listeSalles) {
        jComboBox2.addItem(s.getNom() + " (" + s.getCapacite() + " pl.)");
    }
}
private void chargerSeances() {
    try {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        List<Seance> seances = seanceService.getAllSeances();
        System.out.println("Chargement de " + seances.size() + " séances");
        
        // Format plus lisible et complet
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        
        for (Seance s : seances) {
            model.addRow(new Object[]{
                s.getId(),
                s.getFilm().getTitre(),
                s.getSalle().getNom(),
                s.getDateProjection().format(formatter), // Date complète
                String.format("%.2f", s.getPrix()), // Prix formaté
                s.getTicketsVendus()
            });
        }
        
        
        // Ajuster automatiquement la largeur des colonnes
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setPreferredWidth(100);
        }
        // Colonne Date plus large
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
        // Colonne Film plus large
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
      ajusterColonnes();  
    } catch (Exception e) {
        e.printStackTrace();
    }
}
private void remplirChampsDepuisTable(int ligne) {
    try {
        int id = (int) jTable1.getValueAt(ligne, 0);
        String filmTitre = jTable1.getValueAt(ligne, 1).toString();
        String salleNom = jTable1.getValueAt(ligne, 2).toString();
        String dateTimeStr = jTable1.getValueAt(ligne, 3).toString();
        String prixStr = jTable1.getValueAt(ligne, 4).toString().replace(",", ".");
        int tickets = (int) jTable1.getValueAt(ligne, 5);
        
        // Nettoyer le prix (enlever "DH" si présent)
        prixStr = prixStr.replace("DH", "").trim();
        double prix = Double.parseDouble(prixStr);
        
        // Sélectionner le film dans la ComboBox
        for (int i = 0; i < listeFilms.size(); i++) {
            if (listeFilms.get(i).getTitre().equals(filmTitre)) {
                jComboBox1.setSelectedIndex(i);
                break;
            }
        }
        
        // Sélectionner la salle dans la ComboBox
        for (int i = 0; i < listeSalles.size(); i++) {
            if (listeSalles.get(i).getNom().equals(salleNom)) {
                jComboBox2.setSelectedIndex(i);
                break;
            }
        }
        
        // Convertir la date
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        LocalDateTime dateTime = LocalDateTime.parse(dateTimeStr, formatter);
        
        Date date = Date.from(dateTime.atZone(ZoneId.systemDefault()).toInstant());
        jDateChooser2.setDate(date);
        
        jSpinner1.setValue(prix);
        jTextField1.setText(String.valueOf(tickets));
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}
private void ajusterColonnes() {
    try {
        // Définir les largeurs préférées pour chaque colonne
        int[] largeurs = {40, 180, 120, 140, 70, 70}; // ID, Film, Salle, Date, Prix, Tickets
        
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setPreferredWidth(largeurs[i]);
        }
        
        // Permettre le défilement horizontal si nécessaire
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}
private void viderChamps() {
    jComboBox1.setSelectedIndex(-1);
    jComboBox2.setSelectedIndex(-1);
    jDateChooser2.setDate(null);
    jSpinner1.setValue(50.0);
    jTextField1.setText("");
    jTable1.clearSelection();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
