/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cinema.ui;

import com.cinema.services.SeanceService;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.chart.renderer.category.CategoryItemRenderer;
import javax.swing.*;
import java.awt.*;
import java.text.DecimalFormat;
import java.util.List;

public class StatsForm extends javax.swing.JInternalFrame {
    
    private SeanceService seanceService = new SeanceService();
    private JPanel chartPanel;

public StatsForm() {
    initComponents();
    setTitle("Statistiques des recettes");
    setSize(900, 650); // ← CHANGER ICI (taille plus grande)
    setLocation(50, 50);
    setClosable(true);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    
    // Charger et afficher le graphique
    afficherGraphique();
}
    
private void afficherGraphique() {
    try {
        System.out.println("=== CHARGEMENT DES STATISTIQUES ===");
        
        // Récupérer les vraies données de la base
        List<Object[]> recettes = seanceService.getMonthlyRevenue();
        System.out.println("Nombre de mois avec recettes: " + recettes.size());
        
        // AFFICHER LES DONNÉES BRUTES
        for (Object[] row : recettes) {
            System.out.println("Donnée brute - Année: " + row[0] + ", Mois: " + row[1] + ", Total: " + row[2]);
        }
        
        // Créer le dataset
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        if (!recettes.isEmpty()) {
            for (Object[] row : recettes) {
                int annee = (int) row[0];
                int mois = (int) row[1];
                double total = (double) row[2];
                
                String moisNom = getMoisNom(mois);
                String anneeMois = moisNom + " " + annee;
                
                System.out.println("Ajout au dataset: " + anneeMois + " = " + total + " DH");
                dataset.addValue(total, "Recettes", anneeMois);
            }
        } else {
            System.out.println("⚠️ AUCUNE DONNÉE TROUVÉE DANS LA BASE !");
            dataset.addValue(0, "Recettes", "Aucune donnée");
        }
        
        // Créer le graphique
        JFreeChart chart = ChartFactory.createBarChart(
            "Recettes mensuelles", "Mois", "Montant (DH)", 
            dataset, PlotOrientation.VERTICAL, true, true, false
        );
        
        chart.setBackgroundPaint(Color.WHITE);
        
        ChartPanel panel = new ChartPanel(chart);
        panel.setPreferredSize(new Dimension(800, 500));
        
        this.getContentPane().removeAll();
        this.getContentPane().setLayout(new BorderLayout());
        this.getContentPane().add(panel, BorderLayout.CENTER);
        
        JButton btnRefresh = new JButton("Rafraîchir");
        btnRefresh.addActionListener(e -> afficherGraphique());
        this.getContentPane().add(btnRefresh, BorderLayout.SOUTH);
        
        this.revalidate();
        this.repaint();
        
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur: " + e.getMessage());
    }
} 
    private String getMoisNom(int mois) {
        String[] moisNoms = {
            "Janvier", "Février", "Mars", "Avril", "Mai", "Juin",
            "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"
        };
        return (mois >= 1 && mois <= 12) ? moisNoms[mois - 1] : "Mois " + mois;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Statistiques");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
